# Generated by Django 3.2.9 on 2021-11-28 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=128, verbose_name='имя продукта')),
                ('receipt_date', models.DateTimeField(auto_now_add=True, verbose_name='дата поступления')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='цена продукта')),
                ('unit', models.CharField(max_length=10, verbose_name='единица измерения')),
                ('provider', models.CharField(max_length=50, verbose_name='поставщик')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.category')),
                ('category1', models.ManyToManyField(related_name='category1', to='mainapp.Category')),
            ],
        ),
    ]
